### ISSUE TITLE
Value requirement of bool option

### ISSUE THREAD

**Issue by yunusemredilber** [at-grandpa/clim#87]
I think if an option's type is boolean, we shouldn't get an error to give a value as a parameter. Current workflow:
```cr
option "-ws", "--with-something", type: Bool, desc: "Integrates something"
run do |opts, args|
  puts opts.with_something
end
```

```bash
$ app --with-something
ERROR: Bool arguments accept only "true" or "false". Input: [g]

Please see the `--help`.
```

Desired behavior:
```bash
$ ./app --with-something
true
$ ./app
false
```

**Comment by at-grandpa** [comment]
Thank you for your comment. 😃 
I'll look into it.

**Comment by at-grandpa** [comment]
@yunusemredilber 
I’m sorry for the late reply.

The reason is that you were using a multi-character short_flag with the `Bool` type. If you fix `-ws` to `-w`, it will work as intended.

-------------

In clim, short_flag with multiple characters is hard to handle in the case of `Bool` type. This is because multi-character short_flags are interpreted as "options with required arguments" by crystal's `OptionParser`.

See:
https://github.com/crystal-lang/crystal/blob/479b77dd11725473838a8dab792b9013fdaa7a1c/spec/std/option_parser_spec.cr#L49

If an option with a required argument is specified with the clim `Bool` type, only `true` or `false` arguments will be accepted. 

See:
https://github.com/at-grandpa/clim/blob/954fbebb9b705f7f598570e3e2cee54ab4577577/src/clim/types.cr#L77-L79

Try to run the following code. If true or false is given as an argument, no error will occur.

_src/issue87.cr_

```crystal
require "clim"

class Cli < Clim
  main do
    # It is the same as your code.
    option "-ws", "--with-something", type: Bool, desc: "Integrates something"
    run do |opts, args|
      puts opts.with_something
    end
  end
end

Cli.start(ARGV)
```

```shell
$ crystal run src/issue87.cr -- -ws
ERROR: Bool arguments accept only "true" or "false". Input: [s]

Please see the `--help`.
$ crystal run src/issue87.cr -- -w true
true
$ crystal run src/issue87.cr -- -wtrue
true
$ crystal run src/issue87.cr -- --with-something
ERROR: Option that requires an argument. "--with-something"

Please see the `--help`.
$ crystal run src/issue87.cr -- --with-something false
false
$ crystal run src/issue87.cr -- --with-something=false
false
$                                      
```

If you fix `-ws` to `-w`, it will work as intended.

_src/issue87.cr_

```crystal
require "clim"

class Cli < Clim
  main do
    # Fixed `-ws` to `-w`.
    option "-w", "--with-something", type: Bool, desc: "Integrates something"
    run do |opts, args|
      puts opts.with_something
    end
  end
end

Cli.start(ARGV)
```

```shell
$ crystal run src/issue87.cr -- -w
true
$ crystal run src/issue87.cr -- --with-something
true
$ crystal run src/issue87.cr --
false
$                                   
```

**Comment by yunusemredilber** [comment]
@at-grandpa It's clear now. Thanks a lot for your time and detailed explanation!
